-- ============================================================================
-- Tagref (asset-label ordering) moves into this database. Same tables and
-- columns as the original Tagref project, prefixed `tagref_` so they can't
-- clash with ProofPod modules. Tagref's app reaches these with the server-side
-- service-role key only, so RLS is ON with no policies and all access is
-- revoked from the anon/authenticated roles — signed-in ProofPod users cannot
-- read or write any of this through the API.
-- Data is loaded separately (not via a migration: it's customer data).
-- Run after 0001-0021.
-- ============================================================================

create sequence if not exists public.tagref_asset_id_seq start 100117;

create table if not exists public.tagref_clients (
  client_id   bigint generated by default as identity primary key,
  client_name text not null,
  created_at  timestamptz not null default now()
);

create table if not exists public.tagref_contractors (
  contractor_id bigint generated by default as identity primary key,
  company_name  text not null,
  created_at    timestamptz not null default now()
);

create table if not exists public.tagref_sites (
  site_id    bigint generated by default as identity primary key,
  client_id  bigint not null references public.tagref_clients (client_id),
  site_name  text not null,
  address    text,
  created_at timestamptz not null default now()
);

create table if not exists public.tagref_orders (
  order_id      bigint generated by default as identity primary key,
  site_id       bigint not null references public.tagref_sites (site_id),
  contractor_id bigint not null references public.tagref_contractors (contractor_id),
  submitted_at  timestamptz not null default now(),
  status        text not null default 'received'
                  check (status in ('received', 'in_production', 'shipped', 'cancelled')),
  notes         text
);

create table if not exists public.tagref_refrigerants (
  refrigerant_code text primary key,
  gwp              numeric(10,2) not null,
  active           boolean not null default true,
  updated_at       timestamptz not null default now()
);

create table if not exists public.tagref_assets (
  asset_id   bigint primary key default nextval('public.tagref_asset_id_seq'),
  label_type text not null
               check (label_type in ('fgas', 'asset_tag', 'electrical', 'custom', 'valve')),
  site_id    bigint not null references public.tagref_sites (site_id),
  order_id   bigint references public.tagref_orders (order_id),
  area       text,
  status     text not null default 'active' check (status in ('active', 'superseded')),
  created_at timestamptz not null default now()
);
alter sequence public.tagref_asset_id_seq owned by public.tagref_assets.asset_id;

create table if not exists public.tagref_asset_tag_details (
  asset_id  bigint primary key references public.tagref_assets (asset_id),
  reference text
);

create table if not exists public.tagref_fgas_details (
  asset_id           bigint primary key references public.tagref_assets (asset_id),
  system_id          text,
  commissioning_date date,
  refrigerant_type   text not null references public.tagref_refrigerants (refrigerant_code),
  total_charge_kg    numeric(6,2) not null,
  co2_equivalent     numeric(10,2) not null
);

create table if not exists public.tagref_valve_details (
  asset_id  bigint primary key references public.tagref_assets (asset_id) on delete cascade,
  reference text
);

create table if not exists public.tagref_electrical_details (
  asset_id  bigint primary key references public.tagref_assets (asset_id),
  reference text,
  fed_from  text,
  zs        numeric(6,3),
  pfc       numeric(8,2)
);

create table if not exists public.tagref_custom_details (
  asset_id bigint primary key references public.tagref_assets (asset_id),
  line_1   text,
  line_2   text,
  line_3   text,
  line_4   text,
  line_5   text
);

create table if not exists public.tagref_asset_attachments (
  attachment_id             bigint generated by default as identity primary key,
  asset_id                  bigint not null references public.tagref_assets (asset_id),
  attachment_type           text check (attachment_type in
                              ('photo', 'om_manual', 'commissioning_cert', 'service_record', 'engineer_note', 'other')),
  file_path                 text not null,
  description               text,
  uploaded_by_contractor_id bigint references public.tagref_contractors (contractor_id),
  uploaded_at               timestamptz not null default now()
);

create table if not exists public.tagref_refrigerant_requests (
  request_id     bigint generated by default as identity primary key,
  requested_code text not null,
  requested_gwp  numeric(10,2),
  contractor_id  bigint references public.tagref_contractors (contractor_id),
  status         text not null default 'pending' check (status in ('pending', 'fulfilled', 'rejected')),
  admin_notes    text,
  requested_at   timestamptz not null default now(),
  resolved_at    timestamptz
);

create table if not exists public.tagref_site_access (
  site_access_id bigint generated by default as identity primary key,
  site_id        bigint not null references public.tagref_sites (site_id),
  contractor_id  bigint not null references public.tagref_contractors (contractor_id),
  granted_at     timestamptz not null default now(),
  granted_method text,
  revoked_at     timestamptz
);

-- Lock everything down: RLS on (no policies) and no API-role access at all.
do $$
declare t text;
begin
  for t in select tablename from pg_tables
           where schemaname = 'public' and tablename like 'tagref\_%' escape '\'
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
  end loop;
end $$;
revoke all on sequence public.tagref_asset_id_seq from anon, authenticated;
